"""Provider-neutral task adapter SDK."""

from .contracts import (
    ABSENT_REVISION,
    ChangeSet,
    InvalidRequest,
    InvalidTransition,
    ResolveResult,
    RevisionConflict,
    TaskChange,
    TaskNotFound,
    TaskSink,
    TaskSnapshot,
    TaskSource,
    WriteRequest,
    WriteResult,
)
from .dependencies import (
    TASK_ADAPTER_CONTRACT_VERSION,
    AdapterDependency,
    DependencyCheck,
    DependencyUnavailable,
    SINK_CAPABILITIES,
    SOURCE_CAPABILITIES,
    check_dependency,
    require_dependency,
)

__all__ = [
    "ABSENT_REVISION",
    "AdapterDependency",
    "ChangeSet",
    "DependencyCheck",
    "DependencyUnavailable",
    "InvalidRequest",
    "InvalidTransition",
    "ResolveResult",
    "RevisionConflict",
    "SINK_CAPABILITIES",
    "SOURCE_CAPABILITIES",
    "TASK_ADAPTER_CONTRACT_VERSION",
    "TaskChange",
    "TaskNotFound",
    "TaskSink",
    "TaskSnapshot",
    "TaskSource",
    "WriteRequest",
    "WriteResult",
    "check_dependency",
    "require_dependency",
]
